### ISSUE TITLE
URL change for pandoc

### ISSUE THREAD

**Issue by jgm** [babelmark/babelmark-registry#17]
Hi, I wonder if you can change the URLs for pandoc?

for pandoc 'markdown':
```
https://pandoc.org/cgi-bin/pandoc-server.cgi/babelmark?from=markdown&to=html5&text=foo
```

for pandoc 'markdown_strict':
```
https://pandoc.org/cgi-bin/pandoc-server.cgi/babelmark?from=markdown_strict&to=html5&text=foo
```

Thanks!

Btw, I've decided to stop maintaining babelmark 2, and point people here instead: https://johnmacfarlane.net/babelmark2/

**Comment by jgm** [comment]
I would have submitted a PR, but I wasn't sure how the encryption worked.

**Comment by xoofx** [comment]
I have updated the URL, though they seem currently not accessible.

**Comment by jgm** [comment]
Oh, I guess I set it up to accept a JSON payload, not form data.
I will have to fix that, sorry.

**Comment by jgm** [comment]
I have fixed the server and it is working properly in babelmark 3.
